import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'auth.signInWithGoogle': 'Sign in with Google',
    'auth.title': 'Sign in to save your data',
    'auth.description': 'Create an account to save your processed commands and access them from any device.',
    'auth.googleSignInComingSoon': 'Google Sign In Coming Soon',
    'auth.featureComingSoon': 'This feature will be available soon!',
    'language.switchTo': 'Switch to',
    'language.english': 'English',
    'language.spanish': 'Spanish',
    'nav.features': 'Features',
    'nav.howItWorks': 'How It Works',
    'nav.pricing': 'Pricing',
    'nav.tryNow': 'Free Trial',
    'nav.signIn': 'Sign In',
    'nav.signUp': 'Sign Up',
    'demo.processingTitle': 'Command Processing',
    'demo.title': 'Convert Commands to Excel',
    'demo.description': 'Take a photo or upload an image of your command to generate an Excel file automatically',
    'demo.captureTitle': 'Capture the Command',
    'demo.captureButton': 'Use Camera',
    'demo.uploadButton': 'Upload Image',
    'demo.addCommandButton': 'Add Command',
    'demo.previewTitle': 'Preview',
    'demo.exportButton': 'Export to Excel',
    'demo.noCommands': 'No commands processed yet',
    'demo.productColumn': 'Product',
    'demo.quantityColumn': 'Quantity',
    'demo.priceColumn': 'Price',
    'demo.totalColumn': 'Total',
    'demo.totalItems': 'Total Items',
    'demo.totalAmount': 'Total Amount',
    'process.title': 'How It Works',
    'process.heading': 'From Paper to Spreadsheet in 4 Simple Steps',
    'process.subtitle': 'From Paper to Spreadsheet in 4 Simple Steps',
    'process.description': 'HandSheet makes the process of converting handwritten notes to spreadsheet data quick and effortless.',
    'process.step1.title': 'Capture Your Notes',
    'process.step1.description': 'Take a picture of your handwritten notes, lists, or tables with your smartphone or upload an existing image.',
    'process.step2.title': 'AI Processing',
    'process.step2.description': 'Our advanced AI analyzes your handwriting, recognizes text, and identifies table structures automatically.',
    'process.step3.title': 'Review & Edit',
    'process.step3.description': 'Verify the converted data and make any necessary adjustments in our intuitive editor.',
    'process.step4.title': 'Export & Share',
    'process.step4.description': 'Export directly to Excel or Google Sheets with a single click, ready to use immediately.',
    'process.cta': 'Try HandSheet Now',
    'process.ctaSubtext': 'No credit card required. Start converting your handwritten notes today.',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInDescription': 'Enter your credentials to sign in to your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.dontHaveAccount': 'Don\'t have an account?',
    'auth.signUp': 'Sign up',
    'auth.createAccount': 'Create an account',
    'auth.createAccountDescription': 'Enter your information to create an account',
    'auth.name': 'Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.back': 'Back',
    'auth.orContinueWith': 'Or continue with',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.orSignInWith': 'Or sign in with',
    'auth.orSignUpWith': 'Or sign up with',
    'auth.socialText': 'You can also use your social accounts to get started',
    'hero.tagline': 'Handwriting to Spreadsheet Revolution',
    'hero.title': 'Transform Your Handwritten Notes Into Spreadsheet Data',
    'hero.description': 'HandSheet instantly converts your handwritten notes, lists, and tables into perfectly formatted spreadsheets. Save hours of manual data entry with our AI-powered solution.',
    'hero.startFreeTrial': 'Start Free Trial',
    'hero.watchDemo': 'Watch Demo',
    'hero.feature1': 'Handwriting Recognition',
    'hero.feature1Description': 'Advanced AI recognizes even the messiest handwriting with incredible accuracy.',
    'hero.feature2': 'Table Structure Detection',
    'hero.feature2Description': 'Automatically identifies tables, rows, and columns in your handwritten notes.',
    'hero.feature3': 'Direct Sheet Export',
    'hero.feature3Description': 'Export directly to Excel or Google Sheets with formatting intact.',
    'features.title': 'Features',
    'features.heading': 'Powerful Features That Save You Time',
    'features.description': 'HandSheet combines advanced AI technology with intuitive design to transform your handwritten data into perfectly formatted spreadsheets.',
    'features.recognition.badge': 'Intelligent Recognition',
    'features.recognition.title': 'Capture Any Handwriting Style',
    'features.recognition.description': 'Our advanced AI has been trained on millions of handwriting samples to accurately recognize even the most challenging handwriting styles, turning messy notes into clean data.',
    'features.recognition.point1': '99.8% recognition accuracy',
    'features.recognition.point2': 'Works with cursive and print handwriting',
    'features.recognition.point3': 'Supports 40+ languages',
    'features.recognition.point4': 'Preserves mathematical formulas',
    'features.recognition.cta': 'Learn about our recognition technology',
    'features.recognition.imageAlt': 'Handwriting recognition in action',
    'features.structure.badge': 'Smart Structure Detection',
    'features.structure.title': 'Automatic Table Organization',
    'features.structure.description': 'HandSheet intelligently identifies table structures, rows, columns, and cells from your handwritten notes, preserving the exact layout in your spreadsheets.',
    'features.structure.point1': 'Detects tables, grids, and lists automatically',
    'features.structure.point2': 'Preserves row and column relationships',
    'features.structure.point3': 'Recognizes headers and formatting',
    'features.structure.point4': 'Maintains cell merges and spans',
    'features.structure.cta': 'See structure detection in action',
    'features.structure.imageAlt': 'Table and structure detection',
    'features.integration.badge': 'Seamless Integration',
    'features.integration.title': 'Direct Export to Your Favorite Tools',
    'features.integration.description': 'Send your converted data directly to Excel, Google Sheets, or other spreadsheet applications with just one click. No intermediate steps required.',
    'features.integration.point1': 'One-click export to Excel and Google Sheets',
    'features.integration.point2': 'Preserves formulas and functions',
    'features.integration.point3': 'Maintains formatting and styles',
    'features.integration.point4': 'Easy sharing and collaboration options',
    'features.integration.cta': 'Explore integration options',
    'features.integration.imageAlt': 'Seamless export to spreadsheets',
    'cta.title': 'Ready to transform your handwritten data?',
    'cta.description': 'Join the entrepreneurs who save hours every week by automating handwritten note conversion to spreadsheets.',
    'cta.feature1': '14-day free trial with full access to all features',
    'cta.feature2': 'No credit card required to get started',
    'cta.feature3': 'Cancel anytime, no questions asked',
    'cta.primaryButton': 'Start Free Trial',
    'cta.secondaryButton': 'View Pricing',
    'cta.plan.badge': 'Most Popular',
    'cta.plan.title': 'Pro Plan',
    'cta.plan.description': 'Perfect for professionals and small teams',
    'cta.plan.period': '/ month',
    'cta.plan.feature1': 'Unlimited document scans',
    'cta.plan.feature2': 'Advanced table recognition',
    'cta.plan.feature3': 'Direct export to Excel and Google Sheets',
    'cta.plan.feature4': 'Cloud storage for all your documents',
    'cta.plan.feature5': 'Priority customer support',
    'cta.plan.feature6': 'Team collaboration features',
    'cta.plan.cta': 'Get Started',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordDescription': 'Enter your email address and we\'ll send you a link to reset your password.',
    'auth.resetPasswordSuccess': 'Password reset email sent',
    'auth.resetPasswordSuccessDescription': 'Check your email for a link to reset your password. If it doesn\'t appear within a few minutes, check your spam folder.',
    'auth.resetPasswordError': 'Error sending reset email',
    'auth.resetPasswordErrorDescription': 'There was an error sending the reset email. Please try again.',
    'auth.newPassword': 'New Password',
    'auth.confirmNewPassword': 'Confirm New Password',
    'auth.passwordResetSuccess': 'Password reset successful',
    'auth.passwordResetSuccessDescription': 'Your password has been reset successfully. You can now sign in with your new password.',
    'auth.passwordResetError': 'Error resetting password',
    'auth.passwordResetErrorDescription': 'There was an error resetting your password. Please try again.',
    'auth.invalidResetToken': 'Invalid or expired reset token',
    'auth.invalidResetTokenDescription': 'The password reset link is invalid or has expired. Please request a new one.',
    'auth.backToSignIn': 'Back to Sign In',
    'privacy.title': 'Privacy Policy',
    'privacy.collectedInfo': 'Information We Collect',
    'privacy.collectedInfoDesc': 'We collect the following information when you use HandSheet:',
    'privacy.registrationInfo': 'Registration information (name, email)',
    'privacy.commandImages': 'Command images you process',
    'privacy.usageData': 'App usage data',
    'privacy.howWeUse': 'How We Use Your Information',
    'privacy.howWeUseDesc': 'We use your information to:',
    'privacy.provideServices': 'Provide and improve our services',
    'privacy.processCommands': 'Process your commands and generate Excel files',
    'privacy.sendUpdates': 'Send updates and important notifications',
    'privacy.dataDeletion': 'Data Deletion',
    'privacy.dataDeletionDesc': 'You can delete your account and all your data at any time:',
    'privacy.loginStep': 'Log in to your account',
    'privacy.settingsStep': 'Go to Settings > Privacy',
    'privacy.deleteStep': 'Select "Delete account"',
    'privacy.confirmStep': 'Confirm deletion',
    'privacy.deletionNote': 'All your data will be permanently deleted from our servers.',
    'privacy.contact': 'Contact',
    'privacy.contactDesc': 'If you have questions about this privacy policy, contact us at:',
    'privacy.lastUpdated': 'Last updated:',
    'reviews.title': 'What Our Customers Say',
    'reviews.subtitle': 'Trusted by small businesses and entrepreneurs',
    'reviews.review1.name': 'Juan Carlos Rodríguez',
    'reviews.review1.role': 'Restaurant Owner',
    'reviews.review1.comment': 'This tool has revolutionized how we handle our orders. The accuracy is impressive and saves us hours of manual work.',
    'reviews.review2.name': 'María Fernanda López',
    'reviews.review2.role': 'Café Manager',
    'reviews.review2.comment': 'The best investment for our business. The AI recognition is incredibly accurate, even with our messy handwriting.',
    'reviews.review3.name': 'Carlos Andrés Martínez',
    'reviews.review3.role': 'Bar Owner',
    'reviews.review3.comment': 'Simple, fast, and reliable. Exactly what we needed to streamline our order processing.',
    'pricing.currency': 'COP',
    'pricing.amount': '100,000',
    'pricing.period': '/ month',
  },
  es: {
    'auth.signInWithGoogle': 'Iniciar sesión con Google',
    'auth.title': 'Inicia sesión para guardar tus datos',
    'auth.description': 'Crea una cuenta para guardar tus comandos procesados y acceder a ellos desde cualquier dispositivo.',
    'auth.googleSignInComingSoon': 'Inicio de sesión con Google próximamente',
    'auth.featureComingSoon': '¡Esta característica estará disponible pronto!',
    'language.switchTo': 'Cambiar a',
    'language.english': 'Inglés',
    'language.spanish': 'Español',
    'nav.features': 'Características',
    'nav.howItWorks': 'Cómo Funciona',
    'nav.pricing': 'Precios',
    'nav.tryNow': 'Prueba Gratuita',
    'nav.signIn': 'Ingresar',
    'nav.signUp': 'Registrarse',
    'demo.processingTitle': 'Procesamiento de comandas',
    'demo.title': 'Convierte comandas a Excel',
    'demo.description': 'Toma una foto o sube una imagen de tu comanda para generar un Excel automáticamente',
    'demo.captureTitle': 'Captura la comanda',
    'demo.captureButton': 'Usar cámara',
    'demo.uploadButton': 'Subir imagen',
    'demo.addCommandButton': 'Agregar comanda',
    'demo.previewTitle': 'Vista previa',
    'demo.exportButton': 'Exportar a Excel',
    'demo.noCommands': 'Aún no hay comandas procesadas',
    'demo.productColumn': 'Producto',
    'demo.quantityColumn': 'Cantidad',
    'demo.priceColumn': 'Precio',
    'demo.totalColumn': 'Total',
    'demo.totalItems': 'Total de ítems',
    'demo.totalAmount': 'Monto total',
    'process.title': 'Cómo Funciona',
    'process.heading': 'Pasos a Seguir',
    'process.subtitle': 'Del Papel a la Hoja de Cálculo en 4 Pasos Simples',
    'process.description': 'HandSheet hace que el proceso de convertir notas manuscritas en datos de hoja de cálculo sea rápido y sin esfuerzo.',
    'process.step1.title': 'Captura tus Notas',
    'process.step1.description': 'Toma una foto de tus notas manuscritas, listas o tablas con tu smartphone o sube una imagen existente.',
    'process.step2.title': 'Procesamiento IA',
    'process.step2.description': 'Nuestra IA avanzada analiza tu escritura, reconoce texto e identifica estructuras de tablas automáticamente.',
    'process.step3.title': 'Revisar y Editar',
    'process.step3.description': 'Verifica los datos convertidos y realiza los ajustes necesarios en nuestro editor intuitivo.',
    'process.step4.title': 'Exportar y Compartir',
    'process.step4.description': 'Exporta directamente a Excel o Google Sheets con un solo clic, listo para usar inmediatamente.',
    'process.cta': 'Prueba HandSheet Ahora',
    'process.ctaSubtext': 'No se requiere tarjeta de crédito. Comienza a convertir tus notas manuscritas hoy.',
    'auth.welcomeBack': '¡Bienvenido de nuevo!',
    'auth.signInDescription': 'Ingresa tus credenciales para iniciar sesión en tu cuenta',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.signIn': 'Iniciar sesión',
    'auth.dontHaveAccount': '¿No tienes una cuenta?',
    'auth.signUp': 'Regístrate',
    'auth.createAccount': 'Crear una cuenta',
    'auth.createAccountDescription': 'Ingresa tu información para crear una cuenta',
    'auth.name': 'Nombre',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'auth.back': 'Volver',
    'auth.orContinueWith': 'O continuar con',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.orSignInWith': 'O iniciar sesión con',
    'auth.orSignUpWith': 'O registrarse con',
    'auth.socialText': 'También puedes usar tus cuentas sociales para comenzar',
    'hero.tagline': 'Revolución de Escritura a Hoja de Cálculo',
    'hero.title': 'Transforma tus Notas Manuscritas en Datos de Hoja de Cálculo',
    'hero.description': 'HandSheet convierte instantáneamente tus notas manuscritas, listas y tablas en hojas de cálculo perfectamente formateadas. Ahorra horas de entrada manual de datos con nuestra solución impulsada por IA.',
    'hero.startFreeTrial': 'Comenzar Prueba Gratuita',
    'hero.watchDemo': 'Ver Demostración',
    'hero.feature1': 'Reconocimiento de Escritura',
    'hero.feature1Description': 'IA avanzada reconoce incluso la escritura más desordenada con precisión increíble.',
    'hero.feature2': 'Detección de Estructura de Tablas',
    'hero.feature2Description': 'Identifica automáticamente tablas, filas y columnas en tus notas manuscritas.',
    'hero.feature3': 'Exportación Directa',
    'hero.feature3Description': 'Exporta directamente a Excel o Google Sheets con el formato intacto.',
    'features.title': 'Características',
    'features.heading': 'Potentes Características que te Ahorran Tiempo',
    'features.description': 'HandSheet combina tecnología avanzada de IA con un diseño intuitivo para transformar tus datos manuscritos en hojas de cálculo perfectamente formateadas.',
    'features.recognition.badge': 'Reconocimiento Inteligente',
    'features.recognition.title': 'Captura Cualquier Estilo de Escritura',
    'features.recognition.description': 'Nuestra IA avanzada ha sido entrenada con millones de muestras de escritura a mano para reconocer con precisión incluso los estilos de escritura más desafiantes, convirtiendo notas desordenadas en datos limpios.',
    'features.recognition.point1': '99.8% de precisión en el reconocimiento',
    'features.recognition.point2': 'Funciona con escritura cursiva e imprenta',
    'features.recognition.point3': 'Compatible con más de 40 idiomas',
    'features.recognition.point4': 'Preserva fórmulas matemáticas',
    'features.recognition.cta': 'Aprende sobre nuestra tecnología de reconocimiento',
    'features.recognition.imageAlt': 'Reconocimiento de escritura en acción',
    'features.structure.badge': 'Detección Inteligente de Estructura',
    'features.structure.title': 'Organización Automática de Tablas',
    'features.structure.description': 'HandSheet identifica de manera inteligente estructuras de tablas, filas, columnas y celdas de tus notas manuscritas, preservando la disposición exacta en tus hojas de cálculo.',
    'features.structure.point1': 'Detecta tablas, cuadrículas y listas automáticamente',
    'features.structure.point2': 'Preserva relaciones entre filas y columnas',
    'features.structure.point3': 'Reconoce encabezados y formato',
    'features.structure.point4': 'Mantiene la combinación y extensión de celdas',
    'features.structure.cta': 'Ver detección de estructura en acción',
    'features.structure.imageAlt': 'Detección de tablas y estructura',
    'features.integration.badge': 'Integración Perfecta',
    'features.integration.title': 'Exportación Directa a tus Herramientas Favoritas',
    'features.integration.description': 'Envía tus datos convertidos directamente a Excel, Google Sheets u otras aplicaciones de hojas de cálculo con solo un clic. No se requieren pasos intermedios.',
    'features.integration.point1': 'Exportación con un clic a Excel y Google Sheets',
    'features.integration.point2': 'Preserva fórmulas y funciones',
    'features.integration.point3': 'Mantiene el formato y los estilos',
    'features.integration.point4': 'Opciones fáciles para compartir y colaborar',
    'features.integration.cta': 'Explorar opciones de integración',
    'features.integration.imageAlt': 'Exportación perfecta a hojas de cálculo',
    'cta.title': '¿Listo para transformar tus datos manuscritos?',
    'cta.description': 'Únete a los emprendedores que ahorran horas cada semana automatizando la conversión de notas manuscritas a hojas de cálculo.',
    'cta.feature1': 'Prueba gratuita de 14 días con acceso completo a todas las funciones',
    'cta.feature2': 'No se requiere tarjeta de crédito para comenzar',
    'cta.feature3': 'Cancela cuando quieras, sin preguntas',
    'cta.primaryButton': 'Iniciar Prueba Gratuita',
    'cta.secondaryButton': 'Ver Precios',
    'cta.plan.badge': 'Más Popular',
    'cta.plan.title': 'Plan Pro',
    'cta.plan.description': 'Perfecto para profesionales y equipos pequeños',
    'cta.plan.period': '/ mes',
    'cta.plan.feature1': 'Escaneos de documentos ilimitados',
    'cta.plan.feature2': 'Reconocimiento avanzado de tablas',
    'cta.plan.feature3': 'Exportación directa a Excel y Google Sheets',
    'cta.plan.feature4': 'Almacenamiento en la nube para todos tus documentos',
    'cta.plan.feature5': 'Soporte prioritario al cliente',
    'cta.plan.feature6': 'Funciones de colaboración para equipos',
    'cta.plan.cta': 'Comenzar',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.resetPassword': 'Recuperar Contraseña',
    'auth.resetPasswordDescription': 'Ingresa tu correo electrónico y te enviaremos un enlace para restablecer tu contraseña.',
    'auth.resetPasswordSuccess': 'Correo de recuperación enviado',
    'auth.resetPasswordSuccessDescription': 'Revisa tu correo electrónico para encontrar el enlace de recuperación. Si no aparece en unos minutos, revisa tu carpeta de spam.',
    'auth.resetPasswordError': 'Error al enviar el correo',
    'auth.resetPasswordErrorDescription': 'Hubo un error al enviar el correo de recuperación. Por favor, intenta de nuevo.',
    'auth.newPassword': 'Nueva Contraseña',
    'auth.confirmNewPassword': 'Confirmar Nueva Contraseña',
    'auth.passwordResetSuccess': 'Contraseña actualizada',
    'auth.passwordResetSuccessDescription': 'Tu contraseña ha sido actualizada exitosamente. Ahora puedes iniciar sesión con tu nueva contraseña.',
    'auth.passwordResetError': 'Error al actualizar la contraseña',
    'auth.passwordResetErrorDescription': 'Hubo un error al actualizar tu contraseña. Por favor, intenta de nuevo.',
    'auth.invalidResetToken': 'Enlace inválido o expirado',
    'auth.invalidResetTokenDescription': 'El enlace de recuperación es inválido o ha expirado. Por favor, solicita uno nuevo.',
    'privacy.title': 'Política de Privacidad',
    'privacy.collectedInfo': 'Información que recopilamos',
    'privacy.collectedInfoDesc': 'Recopilamos la siguiente información cuando utilizas HandSheet:',
    'privacy.registrationInfo': 'Información de registro (nombre, correo electrónico)',
    'privacy.commandImages': 'Imágenes de comandos que procesas',
    'privacy.usageData': 'Datos de uso de la aplicación',
    'privacy.howWeUse': 'Cómo usamos tu información',
    'privacy.howWeUseDesc': 'Utilizamos tu información para:',
    'privacy.provideServices': 'Proporcionar y mejorar nuestros servicios',
    'privacy.processCommands': 'Procesar tus comandos y generar archivos Excel',
    'privacy.sendUpdates': 'Enviar actualizaciones y notificaciones importantes',
    'privacy.dataDeletion': 'Eliminación de datos',
    'privacy.dataDeletionDesc': 'Puedes eliminar tu cuenta y todos tus datos en cualquier momento:',
    'privacy.loginStep': 'Inicia sesión en tu cuenta',
    'privacy.settingsStep': 'Ve a Configuración > Privacidad',
    'privacy.deleteStep': 'Selecciona "Eliminar cuenta"',
    'privacy.confirmStep': 'Confirma la eliminación',
    'privacy.deletionNote': 'Todos tus datos serán eliminados permanentemente de nuestros servidores.',
    'privacy.contact': 'Contacto',
    'privacy.contactDesc': 'Si tienes preguntas sobre esta política de privacidad, contáctanos en:',
    'privacy.lastUpdated': 'Última actualización:',
    'reviews.title': 'Lo que Dicen Nuestros Clientes',
    'reviews.subtitle': 'Confiado por emprendedores y negocios pequeños',
    'reviews.review1.name': 'Juan Carlos Rodríguez',
    'reviews.review1.role': 'Dueño de Restaurante',
    'reviews.review1.comment': 'Esta herramienta ha revolucionado cómo manejamos nuestros pedidos. La precisión es impresionante y nos ahorra horas de trabajo manual.',
    'reviews.review2.name': 'María Fernanda López',
    'reviews.review2.role': 'Gerente de Café',
    'reviews.review2.comment': 'La mejor inversión para nuestro negocio. El reconocimiento por IA es increíblemente preciso, incluso con nuestra escritura desordenada.',
    'reviews.review3.name': 'Carlos Andrés Martínez',
    'reviews.review3.role': 'Dueño de Bar',
    'reviews.review3.comment': 'Simple, rápido y confiable. Exactamente lo que necesitábamos para agilizar nuestro procesamiento de pedidos.',
    'pricing.currency': 'COP',
    'pricing.amount': '100.000',
    'pricing.period': '/ mes',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 